services:
  - type: redis
    name: copilot-redis
    region: oregon
    maxmemoryPolicy: noeviction

  - type: worker
    name: copilot-worker
    runtime: ruby
    region: oregon
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -e production
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: copilot-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: web
    name: copilot-web
    runtime: ruby
    region: oregon
    buildCommand: bundle install
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e production
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: copilot-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
