# fly.toml file generated for aigc-copilot on 2023-03-31T13:38:31+08:00

app = "copilot-worker-sjc"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sjc"

[env]

[experimental]
  auto_rollback = true
  cmd = ["bundle", "exec", "sidekiq"]
